---
title: "Arbeidskrav 3"
author: "Emilie"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

### Last ned pakker #####

library(tidyverse)
library(broom)
library(kableExtra)

### Last inn data ####
hypertrophy <- read.csv("./data/hypertrophy-kopi.csv", na = NA)

### Valg av data ####
var_interest <- c("CLUSTER", "AVG_CSA_T1")

dat1 <- hypertrophy %>%
  select(all_of(var_interest)) %>%
  mutate(CLUSTER = factor(CLUSTER, levels = c("LOW", "HIGH"))) %>%
  drop_na(CLUSTER, AVG_CSA_T1)
 









```


```{r echo=FALSE, message=FALSE, warning=FALSE}
### T-test ####
ttest <- t.test(AVG_CSA_T1 ~ CLUSTER, paired = FALSE, data = dat1, var.equal = TRUE)

tidy(ttest) %>%
  select(-estimate, -alternative, -method) %>%
  kable(col.names = c("Gj.snitt LOW", "Gj.snitt HIGH", "T-verdi", "P-verdi", "DF", "CI LOW",  "CI High"),
  digits = c(1, 1, 2, 3, 0, 2, 2))

```



```{r echo=FALSE, message=FALSE, warning=FALSE}

### Regression model ######

regmod <- lm(AVG_CSA_T1 ~ CLUSTER, data = dat1)

tidy(regmod) %>%
  kable(col.names = c("", "Estimate", "SE", "t-statistic", "p-value"), 
        digits = c(NA, 1, 1, 2, 3)) 



```

## DEL 2 

```{r echo=FALSE, message=FALSE, warning=FALSE} 


## Regresjonsanalyse 

dat <- read_csv("./data/hypertrophy-kopi.csv") %>%
  select("SUB_ID", "Squat_3RM_kg", "AVG_CSA_T1", "T1_BODY_MASS")





```


```{r echo=FALSE, message=FALSE, warning=FALSE}

### FIGUR ### Skal denne være med? 
dat %>%
  ggplot(aes(Squat_3RM_kg,AVG_CSA_T1 )) + geom_point() + theme_minimal() + 
geom_smooth(se = FALSE, method = "lm")

# Store the correlation analysis in an object 
c <- cor.test(dat$AVG_CSA_T1, dat$Squat_3RM_kg)
# store the regression model
rm <- lm(Squat_3RM_kg ~ AVG_CSA_T1 + T1_BODY_MASS data = dat)

# Display the p-value for the regression coefficient
coef(summary(rm))[2, 4] 
# Display the p-value for the correlation coefficient
c$p.value

summary(rm)$r.squared

c$estimate^2

confint(rm)


```

```{r echo=FALSE, message=FALSE, warning=FALSE}



### Tabell 
dat %>%
  ggplot(aes(rank(AVG_CSA_T1),
             rank(Squat_3RM_kg))) + geom_point() + theme_minimal() +
geom_smooth(se = FALSE, method = "lm")


#### at tallene er normalt fordelt 

cor.test(rank(dat$AVG_CSA_T1), rank(dat$Squat_3RM_kg), method = "pearson")

#### SKAl vi ha med rank eller ikke?? 


## en person med høy kroppsvekt løfter mere, sjekke med kroppsvekt 
```

